### ISSUE TITLE
Can messages be good?

### ISSUE THREAD

**Issue by brendo** [vfile/vfile#17]
Having a quick look through the history of this project, it looks like messages were once a way to raise warnings or errors. The deprecation of `warn` though makes me think that messages could be one way to have an 'audit trail' of what has occurred to a file.

Would it be possible to add a `type` or `level` to a message so that libraries downstream, such as `vfile-reporter` can be a little smarter than just [fatal or warning](https://github.com/vfile/vfile-reporter/blob/master/index.js#L137)?

Or is that not the intentions of `messages`?

**Comment by wooorm** [comment]
VFile only dictates `fatal: true` as meaning a file is no longer processable. As the `fatal` property is an optional boolean, it has three states: nully (`null`/`undefined`), `false`, or `true`.
No plugin/linter actually creates “positive” messages yet, so there hasn’t been any need to deal with that, but some related projects [do support it](https://github.com/unifiedjs/unified-engine-atom/blob/a861c6428f0e84f46c1079715646051d4e86c169/index.js#L99-L104).

I welcome any PR to projects to support this, or docs to include this!

Does that answer your question?

**Comment by wooorm** [comment]
Oh I meant to close this, but feel free to comment if you don‘t agree!
