### ISSUE TITLE
Add posix option to constructor

### ISSUE THREAD

**Issue by mojavelinux** [vfile/vfile#24]
### Subject of the issue

Since we're talking about virtual files, it can often be essential to work with paths that are stable across systems. Currently, path calculations (e.g., `path.join`) are platform dependent. The vfile constructor should honor a posix option that switches a vfile instance from using path to [path.posix](https://nodejs.org/api/path.html#path_path_posix). That way, even on Windows, the path is always computed the same way, as a posix path (a path containing only forward slashes).

### Your environment

OS: Fedora (Linux)
Node: v8.9.4
npm: 5.6.0

### Steps to reproduce

Run the following on a Windows machine:

```js
const File = require('vfile')
const f = new File({ path: 'foo/bar/file.txt' })
f.dirname = 'foo/baz'
console.log(f.path)
```

### Expected behaviour

I want the script to output the following on Windows (if the proposed posix option is set):

```
foo/baz/file.txt
```

### Actual behaviour

On Windows, the script outputs:

```
foo\baz\file.txt
```

### Additional information

If the posix option is set, the path should also be normalized by changing all backslashes to forward slashes if the platform is win32.

**Comment by wooorm** [comment]
Could we do this without affecting the bundled size in browsers too much?

**Comment by mojavelinux** [comment]
Yes, this would be extremely straightforward. The only function from path used in vfile that you have to worry about is `path.join`. All this function does is concatenate two strings on the `path.sep`. We could introduce a private function to replace it that joins on forward slash instead of path.sep when posix mode is enabled.

The assertPart function would also need to be updated to use a forward slash instead of path.sep when posix mode is enabled.

Technically, all the other path functions used in vfile operate the same regardless of platform (except in strange edge cases when you're on a posix platform and the path contains backslashes, but that's not even allowed in Linux).

---

The other path functions that have different behavior are `path.resolve`, `path.normalize` and `path.relative`, but none of those are currently used in vfile.

**Comment by mojavelinux** [comment]
I think we should add property named `posix` to vfile to track this state. I don't think the property should be writable. By default, it can be false for compatibility reasons.

**Comment by mojavelinux** [comment]
One example where this is immediately useful is using vfile in front of git. In git, paths are represents with forward slashes. If I use vfile backed by a git repository, and the path separator in the path gets changed to backslashes on Windows, then the vfile stops giving me path I can use to interact with the git repository.

**Comment by wooorm** [comment]
Sounds like a plan! Would you like to work on this Dan?

**Comment by mojavelinux** [comment]
I'd be happy to send a proposal. Stay tuned.

**Comment by wooorm** [comment]
See GH-25.
