### ISSUE TITLE
Fail without throwing

### ISSUE THREAD

**Issue by denysdovhan** [vfile/vfile#30]
### Subject of the issue

By default `fail` method throws a message

https://github.com/vfile/vfile/blob/master/index.js#L42

What about a method that would mark a message as `fatal`, but without throwing? Maybe something like `error`? Or maybe add an optional 4th param to the `message` that would allow specifying options like `fatal` and others?

It should be much cleaner and let us avoid constant wrapping in `try {} catch () {}`, for example:

https://github.com/remarkjs/remark-lint/blob/6c1b4cf6b01b5e1ea63ca05f986b17dd03d010bf/packages/unified-lint-rule/index.js#L43-L45

What do you think?

**Comment by wooorm** [comment]
We used to have that mode! But it was a bit weird...
Why not just set 'message.fatal = true'?

**Comment by denysdovhan** [comment]
I use `VFile` to build a linter. I attach messages directly to the file using `file.message` and `file.fail`. It would be much elegant for users to assign error messages to files using a single method, instead of importing `VMessage`, creating a new message, mutating a message with `message.fatal = true` and then attaching it with `vfile.messages.push()` … or using empty `try {} catch () {}` every time we need to add an error message.

In my case, having an alias like `file.error` would help to avoid creating a useless layer of abstraction like `SourceFile` over the `VFile` and wrapping `to-vifle` to use my custom abstraction over a `VFile`.

Here's an example:

https://github.com/everylint/everylint/blob/master/src/linters/scripts/index.js#L18-L22

With using something like `vfile.error`:

```diff
# current solution

- try {
-   file.fail(message, { line, column }, ruleId);
- } catch (e) {
-   // ...
- }

# solution with VMessage

- const message = new VMessage(message, { line, column }, ruleId);
- message.fatal = true;
- file.messages.push(message);

# possible solution 

+ file.error(message, { linem column }, ruleId);
```

**Comment by wooorm** [comment]
Ohh, sorry. My suggestion is instead:

```js
var message = file.message(message, { line, column }, ruleId);
message.fatal = true;
```

(In fact I think the line in `unified-lint-rule` should be like that too!)

And, for your `everylint` example, I suggest:

```js
const fatalities = {2: true, 1: false, 0: null}

report.messages.forEach(({ message, line, column, ruleId, severity }) => {
  const msg = file.message(message, { line, column }, ruleId);
  msg.fatal = fatalities[severity]
});
```

**Comment by denysdovhan** [comment]
Looks better, but it doesn't solve the problem, that:

1. It's a mutation.
2. Users are gonna be able to create their own linters, so exposing `fatalities` to them is not a good solution, because it relies on the internals of messages and `everylint` itself.

**Comment by wooorm** [comment]
> It's a mutation.

True, but why is that a problem? You could also `Object.assign(message, {fatal: ..., url: ..., source: ...})` if you think that’s nicer?

> Users are gonna be able to create their own linters, so exposing fatalities to them is not a good solution, because it relies on the internals of messages and everylint itself.

I’m not proposing to expose `fatalities` to others, rather that you could use it internally to map eslint to vfile!

**Comment by denysdovhan** [comment]
> True, but why is that a problem?

Because we rely on the internals.

Instead of a single method call, we need to additionally mutate an internal parameter. That might be error-prone.

**Comment by wooorm** [comment]
> Because we rely on the internals.

Hmm, I see the [properties](https://github.com/vfile/vfile-message#properties) and [custom properties](https://github.com/vfile/vfile-message#custom-properties) on vfile messages (or on plain errors) as API, instead of “internals”.

Just like that unist specifies a `type` property on plain objects to make it into a unist node, vfile message specifies a `fatal` property on error instances to mark them as fatal, warning, or informational messages!

**Comment by denysdovhan** [comment]
Okay, I got it. Thanks for clarifying!

Seems like a need to build a wrapper over a `VFile`.

**Comment by wooorm** [comment]
Sure! Thanks for checking in!

> Seems like a need to build a wrapper over a VFile.

Interesting, let me know what you code up! 👍

**Comment by denysdovhan** [comment]
> Interesting, let me know what you code up! 👍

Sure! I've seen [ideas](https://github.com/vfile/ideas). I hope `everylint` is gonna be a good example of using `VFile`.
