### ISSUE TITLE
Correwct handeling of paths that are directories?

### ISSUE THREAD

**Issue by Hypercubed** [vfile/vfile#31]
It seems to me that paths that are directories  (not containing a filename nor extension) are not handled correctly.  Not sure if this is a bug or working as desired. My use case is I want to add a stem and ext when the path is only a dirname:

```js
const VFile = require("vfile");

const file = new VFile({ path: '/subdir/' });

console.log(file.path);     // "/subdir/"   OK!
console.log(file.dirname);  // "/"          BUG?  S/B "/subdir"
console.log(file.basename); // "subdir"     BUG?  S/B ""

file.stem = 'index';
file.extname = '.html';

console.log(file.path);     // "/index.html" BUG? S/B "/subdir/index.html"
console.log(file.dirname);  // "/"           BUG? S/B "/subdir"
console.log(file.basename); // "index.html"  OK!
```

**Comment by wooorm** [comment]
A path to a directory is a path to a thing like anything else. Vfile does not store information on whether something is a file, a folder, or anything else. In Unix, I believe, the final slash does nothing other than being a convention (just like extensions being common on files, or dotfiles being hidden by default).

I believe this is working as expected! 🤷‍♂️

**Comment by wooorm** [comment]
I think, to do what you want, you could use:

```js
var vfile = require("vfile")
var file = vfile({ path: '/subdir/' })
file.dirname = file.path
file.basename = 'index.html'
console.log(file.path) //=> "/subdir/index.html"
// Or:
file = vfile({ path: '/subdir/' })
file.path += 'index.html'
console.log(file.path) //=> "/subdir/index.html"
```

**Comment by Hypercubed** [comment]
Yeah, I thin I'll end up doing this:

```js
const file = vfile({ path: '/subdir/' });
if (file.path.slice(-1) === '/')) file.path += 'index.html';
```

My goal is to keep `history[0]` eq to the initial path.

Thanks!

**Comment by wooorm** [comment]
Feel free to change the history if you’d feel like it! For example, I often do `var h = file.history.concat(); /* do multiple changes */ file.history = h`, and that’s fine!

History isn’t in use much, I think most things check `file.history[0]` and the current `file.path` to find out where a file came from and where it moved to upon writing.
I think it could be useful for more stuff in the future, but we can still define the use cases!

**Comment by Hypercubed** [comment]
My use case is that given a path `/subdir/` it needs to be resolved to a file (for example `/subdir/index.md`), but when rendering the page links, should be resolved relitive to `/subdir/` (i,e, `history[0]`).
