### ISSUE TITLE
dependency on path missing

### ISSUE THREAD

**Issue by azizghuloum** [vfile/vfile#35]
### package `path` should be added to dependencies

In `core.js`, there is:
```
var path = require('path')
```

but `path` is not listed in `package.json` `dependencies` section:
```
  "dependencies": {
    "@types/unist": "^2.0.2",
    "is-buffer": "^2.0.0",
    "replace-ext": "1.0.0",
    "unist-util-stringify-position": "^2.0.0",
    "vfile-message": "^2.0.0"
  },
```

### Your environment
I'm using `unified` and `remark` in a react-native project. They depend on `vfile`, which in turn cannot be loaded into react-native because it requires `path`. The error I get is:

```
Unable to resolve module `path` from `/[...]/node_modules/vfile/core.js`: Module `path` does not exist in the Haste module map
```

### Expected behaviour

Importing `unified` should work out of the box.

### Actual behaviour

Importing `unified` adds `vfile` as a dependency, and when used in a react-native project, it does not compile.

### Temporary workaround:

For now, I'm doing `yarn add path` myself to my project in order to get it to compile properly, but I should not need to do that just to use `remark`; all dependencies should be installed automatically.

**Comment by ChristianMurphy** [comment]
`path` is a core module that is included in the Node.js runtime. https://nodejs.org/api/path.html
To use in a browser context ensure that the build system includes a browser compatible polyfill.
