### ISSUE TITLE
@types packages should be in devDependencies

### ISSUE THREAD

**Issue by ybiquitous** [vfile/vfile#36]
### Subject of the issue

There is the same problem as <https://github.com/unifiedjs/unified/issues/45> in the `vfile` package.

https://github.com/vfile/vfile/blob/8f474a27c6347558dc62a67af0de90eaa58ab6fa/package.json#L35

I think that the `@types/unist` dependency should be in `devDependencies` instead of `dependences`.

### Your environment

*   **OS**: macOS Mojave version 10.14.5
*   **Packages**: `vfile@4.0.1` (latest)
*   **Env**: Node 12.6.0 / npm 6.10.1 / npx 6.10.1

### Steps to reproduce

Please execute the following commands in your terminal:

```
$ mkdir work

$ cd work

$ echo '{}' > package.json

$ npm install vfile@4.0.1 typescript@2.9.2
...

$ echo 'var a = 1' > test.ts

$ npx tsc test.ts
node_modules/@types/unist/index.d.ts(31,20): error TS2304: Cannot find name 'unknown'.
node_modules/@types/unist/index.d.ts(40,20): error TS2304: Cannot find name 'unknown'.
node_modules/@types/unist/index.d.ts(97,12): error TS2304: Cannot find name 'unknown'.
```

### Expected behaviour

TypeScript compilation should be successful also with older versions (e.g. `2.9.2`).

### Actual behaviour

TypeScript compilation with the version `2.9.2` fails.

It would be great if the problem could be solved!
Thanks.

**Comment by wooorm** [comment]
I think that makes sense, but: why use a one year old version of typescript? 🤷‍♂️

**Comment by ybiquitous** [comment]
Thanks for your quick reply! 

> why use a one year old version of typescript? 🤷‍♂️

I think that widely-used tools such as [`ts-loader`](https://github.com/TypeStrong/ts-loader) usually need to support quite old versions, for example, for enterprise needs. 😅 
(but I don't know real reasons...)

Please see the `ts-loader` CI configuration:
https://github.com/TypeStrong/ts-loader/blob/53f198f4c425a6e14f0be15cc3a1f57b8f969c69/.travis.yml#L17-L29

**Comment by wooorm** [comment]
OK, well a PR like https://github.com/unifiedjs/unified/commit/3aa5737dac718451b804a4e19526c5cdc268671e would be welcome!

**Comment by ChristianMurphy** [comment]
> I think that the `@types/unist` dependency should be in `devDependencies` instead of `dependences`

:+1: 

---

> TypeScript compilation should be successful also with older versions (e.g. `2.9.2`).

@ybiquitous to be clear, the latest versions of `vfile`, `unified`, and `remark` only support **Typescript 3**.
If they by any chance happen to work on TypeScript 2, great, but that is pure happenstance.
You should operate under the assumption that using latest **TypeScript 2 will not work**.
If you need a guarantee that it will work, please use the previous major version.

**Comment by wooorm** [comment]
I think it’s weird that TS complains about stuff it doesn’t understand when it doesn’t need to. TS isn’t used when linting with `remark-cli` and `remark-validate-links` 🤷‍♂️

**Comment by ChristianMurphy** [comment]
> I think that widely-used tools such as ts-loader usually need to support quite old versions, for example, for enterprise needs.

`ts-loader` does support TypeScript 2.
However their documentation guides people to install latest, and for building `ts-loader` they are using TypeScript 3.
Again, if TypeScript 2 support is needed, use `vfile` version 3, and upgrade to `vfile` version 4 when also upgrading TypeScript to version 3.

**Comment by ybiquitous** [comment]
@ChristianMurphy Thanks for your kind response!

I think your idea (the updating policy) makes sense and I agree with you. 👍 

Because `ts-loader` is a special tool for the TypeScript compilation, I think the tool may be forced to support widely versions (see the [`peerDepdendencies`](https://github.com/TypeStrong/ts-loader/blob/53f198f4c425a6e14f0be15cc3a1f57b8f969c69/package.json#L95-L97)).

Anyway, if `@types/*` dependencies would be removed, `remark` as a linter would be successful. Unless, I'll give up using `remark` on `ts-loader` for linting. 😅

**Comment by ChristianMurphy** [comment]
@ybiquitous a couple thoughts. :thought_balloon: 

First, `remark` version 11 (CLI version 7) is the first that requires TypeScript 3, `remark` version 10 (CLI version 6) should still support still support TypeScript 2, if there are dependencies that don't we can work with you to lock those down, so TypeScript 2 support is preserved on the previous major version

Second for using `remark-lint` remember that you are testing markdown, not typescript.
What I've done in the past, is run remark-lint on only one of the configurations in the build matrix, since Node, TypeScript, and other libraries have no bearing on validity of markdown.
You could run `remark-lint` 11 only in a TypeScript 3 build.
Y

**Comment by ybiquitous** [comment]
@ChristianMurphy Thanks, I understand your thoughts, so I get the following solution, for example:

```yaml
# .travis.yml
install:
  # ...
  - |
    if [ "$TYPESCRIPT" == "typescript@3.5.1" ]; then
      yarn add --dev remark-cli remark-validate-links && npx remark -u validate-links . ;
    fi
  - yarn add $TYPESCRIPT
env:
  - TYPESCRIPT=typescript@3.5.1
```

Pros:
- `ts-loader` don't need to add dependencies for `remark`.
- The CI builds become fast because the lint is executed for only one job.

Cons:
- Some tricky.
- Executions on each local machine become slow because the installation is performed on every lint.
- No lockfile support (e.g. `yarn.lock`).

Is the idea suit for your thoughts?
If so, I don't know whether the `ts-loader` team accept the bit tricky solution, but I'll suggest it. 💪

**Comment by ChristianMurphy** [comment]
> Is the idea suit for your thoughts?

Exactly :+1: 

> If so, I don't know whether the ts-loader team accept the bit tricky solution, but I'll suggest it. :muscle:

Worth a try, if not remark 10 is always an option.

**Comment by wooorm** [comment]
@ChristianMurphy Do you suggest still moving the dependencies to dev-dependencies?

**Comment by ChristianMurphy** [comment]
If it's just for TypeScript 2 support, lean towards not removing `@types/unist`.
It's nice to get `@types/unist` automatically, without needing an extra install step.

**Comment by wooorm** [comment]
Alright, and (how) is that different from https://github.com/unifiedjs/unified/issues/45?

**Comment by ChristianMurphy** [comment]
It isn't, and I'd like to re-add the dependency there as well.

**Comment by wooorm** [comment]
So from both threads, this here, and GH-37, I see mixed feelings.
@ChristianMurphy, @Rokt33r, do you suggest going ahead with this and merging GH-37, if it has docs, or instead rejecting this?

**Comment by ChristianMurphy** [comment]
@wooorm to clarify my position.

I am okay with merging #37.
However, it is not the approach I would prefer, because further downstream, people will need to know to install `@types/unist`, that could happen any number of layers downstream, anyone using `typescript` with `remark`, `rehype`, `retext`, `mdx`, or `redot`, directly or indirectly, will be affected.

**Comment by wooorm** [comment]
I think that makes sense, so closing these two!

**Comment by Rokt33r** [comment]
I would prefer to put it in `devDependencies`. But I don't think it is that important. As long as people using Parcel or Webpack, the type definitions won't be included to compiled code anyway. So I guess we could just leave it for now.
