### ISSUE TITLE
Could not find a declaration file for module 'vfile-message'

### ISSUE THREAD

**Issue by Chersquwn** [vfile/vfile#43]
My project has used stylelint package that depends on this package。It throw an error：

```sh
ERROR in [at-loader] ./node_modules/@types/vfile/index.d.ts:11:31 
    TS7016: Could not find a declaration file for module 'vfile-message'.
```

Here are the dependencies：

```sh
stylelint@^10.1.0:
  dependencies:
    ...
    postcss-markdown "^0.36.0",
    ...
```

```sh
postcss-markdown "^0.36.0":
  dependencies:
    remark "^10.0.1",
    ...
```

```sh
remark@^10.0.1:
  dependencies:
    ...
    unified "^7.0.0",
    ...
```

```sh
unified@^7.0.0:
  dependencies:
    ...
    vfile "^3.0.0",
    ...
```

```sh
{
    "name": "@types/vfile",
    "version": "3.0.2",
    "description": "TypeScript definitions for VFile",
    "license": "MIT",
    "contributors": [
        {
            "name": "bizen241",
            "url": "https://github.com/bizen241",
            "githubUsername": "bizen241"
        },
        {
            "name": "Junyoung Choi",
            "url": "https://github.com/rokt33r",
            "githubUsername": "rokt33r"
        }
    ],
    "main": "",
    "types": "index",
    "repository": {
        "type": "git",
        "url": "https://github.com/DefinitelyTyped/DefinitelyTyped.git"
    },
    "scripts": {},
    "dependencies": {
        "@types/node": "*",
        "@types/unist": "*",
        "@types/vfile-message": "*"
    },
    "typesPublisherContentHash": "bb48d507c93dd3ef78cc32948c63a2e407e0706f185a4c8da2fb862ab259d3b9",
    "typeScriptVersion": "3.0"
}
```

The version of `@types/vfile-message` is "*" that will use the latest verion - v2.0.0, which does not include any declaration file.

How can i resolve it?

**Comment by ChristianMurphy** [comment]
@Chersquwn as of version 2, the typings `vfile-message` are included with the package, and the definitely typed version is deprecated and could cause issues, try removing the `@types/vfile-message` from your _package.json_

**Comment by ChristianMurphy** [comment]
Also were any other customizations made?
`vfile` version 3, depends on `vfile-message` version 1 neither of which include typings.

**Comment by Chersquwn** [comment]
> @Chersquwn as of version 2, the typings for `vfile-message` are included with the package, and the definitely typed version is deprecated and could cause issues, try removing the `@types/vfile-message` from your _package.json_

`@types/vfile-message` is not in my package.json, but in `@types/vfile` package。Other package depends on it。

```sh
unified@^7.0.0:
  ...,
  dependencies:
    "@types/unist" "^2.0.0"
    "@types/vfile" "^3.0.0"
    bail "^1.0.0"
    extend "^3.0.0"
    is-plain-obj "^1.1.0"
    trough "^1.0.0"
    vfile "^3.0.0"
    x-is-string "^0.1.0"
```

**Comment by Chersquwn** [comment]
My project wents well one week ago. When i reinstall dependencies, it works fail. I find that `@type/vfile-message` updated 4 days ago.

[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39562](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39562)

**Comment by ChristianMurphy** [comment]
Something isn't adding up in the dependency tree.
@Chersquwn could you share a link to the project if it's public, or a copy of the full package.json or yarn.lock if you can't share the source?

**Comment by Han-MeiM** [comment]
Sorry, I have the same problem.
![image](https://user-images.githubusercontent.com/27951114/68651533-8edcf280-0562-11ea-8e59-69d395a9e31a.png)

This is my yarn.lock
```
unified@^6.1.2:
  version "6.2.0"
  resolved "https://registry.npm.taobao.org/unified/download/unified-6.2.0.tgz#7fbd630f719126d67d40c644b7e3f617035f6dba"
  integrity sha1-f71jD3GRJtZ9QMZEt+P2FwNfbbo=
  dependencies:
    bail "^1.0.0"
    extend "^3.0.0"
    is-plain-obj "^1.1.0"
    trough "^1.0.0"
    vfile "^2.0.0"
    x-is-string "^0.1.0"

unified@^7.0.0:
  version "7.1.0"
  resolved "https://registry.npm.taobao.org/unified/download/unified-7.1.0.tgz#5032f1c1ee3364bd09da12e27fdd4a7553c7be13"
  integrity sha1-UDLxwe4zZL0J2hLif91KdVPHvhM=
  dependencies:
    "@types/unist" "^2.0.0"
    "@types/vfile" "^3.0.0"
    bail "^1.0.0"
    extend "^3.0.0"
    is-plain-obj "^1.1.0"
    trough "^1.0.0"
    vfile "^3.0.0"
    x-is-string "^0.1.0"

vfile@^2.0.0:
  version "2.3.0"
  resolved "https://registry.npm.taobao.org/vfile/download/vfile-2.3.0.tgz?cache=0&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2Fvfile%2Fdownload%2Fvfile-2.3.0.tgz#e62d8e72b20e83c324bc6c67278ee272488bf84a"
  integrity sha1-5i2OcrIOg8MkvGxnJ47ickiL+Eo=
  dependencies:
    is-buffer "^1.1.4"
    replace-ext "1.0.0"
    unist-util-stringify-position "^1.0.0"
    vfile-message "^1.0.0"

vfile@^3.0.0:
  version "3.0.1"
  resolved "https://registry.npm.taobao.org/vfile/download/vfile-3.0.1.tgz?cache=0&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2Fvfile%2Fdownload%2Fvfile-3.0.1.tgz#47331d2abe3282424f4a4bb6acd20a44c4121803"
  integrity sha1-RzMdKr4ygkJPSku2rNIKRMQSGAM=
  dependencies:
    is-buffer "^2.0.0"
    replace-ext "1.0.0"
    unist-util-stringify-position "^1.0.0"
    vfile-message "^1.0.0"
```

**Comment by wooorm** [comment]
This seems to be a bug with DT, not with `vfile-message`. And an older versions of unified/remark/vfile.

Please raise this issue with DT; it’s not something we can fix here.

**Comment by ChristianMurphy** [comment]
@Chersquwn @Han-MeiM I did some tracing, and as @wooorm mentions the issue is not with vfile itself, but with definitely typed and upstream dependencies.

The ideal solution would be to upgrade https://github.com/eslint/eslint-plugin-markdown and https://github.com/gucong3000/postcss-markdown to use the latest remark + unified + vfile, to get the benefit of the improved typings.

For workarounds:
* https://yarnpkg.com/lang/en/docs/selective-version-resolutions could be used, to pin the typings version.
* You could overlay the typing with a different typing using paths. for example https://github.com/vfile/vfile-message/blob/cb26a473c0a6de7e560dc5b22fbb14d8f6aa6313/types/tsconfig.json#L11
* You could ignore the node_modules folder

Again, not ideal, a better solution would be upgrading https://github.com/eslint/eslint-plugin-markdown and https://github.com/gucong3000/postcss-markdown

**Comment by Han-MeiM** [comment]
@ChristianMurphy Thanks.
However, this issue was discovered during the upgrade process, including the old version also reported an error.

**Comment by Chersquwn** [comment]
@ChristianMurphy Thanks.
