### ISSUE TITLE
Missing result property in VFile types

### ISSUE THREAD

**Issue by gurkerl83** [vfile/vfile#52]
In the unified project, the following commit distinguishes the return value of process and processSync as follows.

https://github.com/unifiedjs/unified/commit/c3ba172708e719baa963ee5826a7c81774a2784e

If the result is of type string, it gets assigned on the property contents. If not, it gets assigned to the property result.

Currently, the VFile typescript definition only defines the property contents. The compatibility will be achieved, extending the typescript interface VFile with the result property of type any.

According to the main responsible of the unified and Vfile project, an extension of the interface is not considered critical.

https://github.com/unifiedjs/unified/issues/88

I will make this change and prepare a merge request tomorrow.

**Comment by gurkerl83** [comment]
I have made the adjustments. The result is now an optional property. The idea was, if the interface VFile is used in other projects to create objects, this change should not lead to a conflict. Tests have passed, but only if the xo NPM dependency is pinned to 0.27. XO has released new releases in the last few days, which are loaded in the unpinned version, and the test is aborted. The feature is rebased and squashed. Maybe someone can have a look at it, thanks!

**Comment by wooorm** [comment]
Released in 4.2.0!
