### ISSUE TITLE
types broken for typescript esm support

### ISSUE THREAD

**Issue by philkunz** [vfile/vfile#76]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.3.2

### Steps to reproduce

The module identifies itself as type=module, yet the corresponding index.d.ts at https://unpkg.com/browse/vfile@5.3.2/lib/index.d.ts on lines 193, 194, 218 and 226 uses non esm compliant imports.
This causes the TypeScript compiler to fail when using new node12 and nodenext moduleResolution modes.

### Expected behavior

should work

### Actual behavior

does not work

**Comment by wooorm** [comment]
What isn’t ESM about those imports?

Stuff works in all our ESM projects. Feel free to propose a solution that works for everyone

**Comment by philkunz** [comment]
@wooorm `import '..'` maps to a directory. There are NO directory imports in esm. Esm ALWAYS requires a file specification with extension. The only exception is through either import maps or node modules, where in both cases additional mappings are needed to tell javascript what explicit file to import.

**Comment by wooorm** [comment]
It works fine in TS in ESM, as the build here shows. If it doesn’t for you, perhaps you should report to TypeScript that they should generate `.d.ts` files that work with nodenext moduleResolution?

**Comment by philkunz** [comment]
@wooorm Have you tried with the new nodenext resolution mode for TypeScript?
Also compare here: https://nodejs.org/api/esm.html
--> Mandatory file extensions

**Comment by philkunz** [comment]
The problem is: You are using a non esm moduleResolution mode for TypeScript -> 'node', while it should be -> 'nodenext' for esm.

**Comment by wooorm** [comment]
To reiterate, feel free to propose a solution that works for everyone.
