### ISSUE TITLE
url module does not export `fileURLToPath`

### ISSUE THREAD

**Issue by chris-kruining** [vfile/vfile#81]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.3.4

### Steps to reproduce

- install remix
  - choose just the basics
  - choose cloudflare pages
- install react-markdown
- use `<ReactMarkdown />` in the UI
- `[ERROR] No matching export in "node-modules-polyfills:url" for import "fileURLToPath"`

### Expected behavior

render the markdown

### Actual behavior

the build fails because `fileURLToPath` could not be resolved from `url`

### Affected runtime and version

16.7.0

### Affected package manager and version

8.5.5

### Affected OS and version

Windows 11

### Build and bundle tools

esbuild, Remix

**Comment by ChristianMurphy** [comment]
`fileURLToPath` is a valid url function https://nodejs.org/api/url.html#urlfileurltopathurl
This is an issue with how remix polyfills `node:url`, not an issue with `vfile`

**Comment by ChristianMurphy** [comment]
Following remixes dependency tree, it looks like https://github.com/ionic-team/rollup-plugin-node-polyfills/blob/master/polyfills/url.js needs to be updated.

**Comment by ChristianMurphy** [comment]
This is being tracked for remix at https://github.com/remix-run/remix/issues/3120
